# Generated by Django 4.1.7 on 2023-04-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auditorium_type_university_building_university_unit_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='info',
            field=models.TextField(verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.university_unit', verbose_name='Подразделение Университета'),
        ),
        migrations.DeleteModel(
            name='Auditorium',
        ),
        migrations.DeleteModel(
            name='Auditorium_Type',
        ),
        migrations.DeleteModel(
            name='University_Building',
        ),
        migrations.DeleteModel(
            name='University_Unit',
        ),
    ]
