# Generated by Django 4.1.7 on 2023-04-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditorium_type_university_building_university_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчетсво'),
        ),
    ]
