# Generated by Django 4.1.7 on 2023-05-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_unit',
            name='abbreviation',
            field=models.CharField(max_length=10, verbose_name='Аббревиатура подразделения'),
        ),
        migrations.AlterField(
            model_name='university_unit',
            name='info',
            field=models.TextField(verbose_name='Информация о подразделения'),
        ),
        migrations.AlterField(
            model_name='university_unit',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название подразделения'),
        ),
    ]
