# Generated by Django 4.1.7 on 2023-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_university_unit_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, null=True, verbose_name='Номер телефона'),
        ),
    ]
