# Generated by Django 4.1.7 on 2023-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_unit',
            name='show_in_timetable',
            field=models.BooleanField(null=True, verbose_name='Выводить в расписании'),
        ),
    ]
