# Generated by Django 4.1.7 on 2023-10-05 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_university_unit_show_in_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_unit',
            name='show_in_timetable',
            field=models.BooleanField(default=False, null=True, verbose_name='Выводить в расписании'),
        ),
    ]
