# Generated by Django 4.1.7 on 2023-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_university_unit_show_in_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='university_unit',
            name='default_show',
            field=models.BooleanField(default=False, null=True, verbose_name='Выводить автоматически в расписании'),
        ),
    ]
