# Generated by Django 4.1.7 on 2023-10-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_university_unit_default_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_unit',
            name='default_show',
            field=models.BooleanField(default=False, verbose_name='Выводить автоматически в расписании'),
        ),
        migrations.AlterField(
            model_name='university_unit',
            name='show_in_timetable',
            field=models.BooleanField(default=False, verbose_name='Выводить в расписании'),
        ),
    ]
