# Generated by Django 4.1.7 on 2023-10-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_university_unit_default_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium_type',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='university_building',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='university_unit',
            name='abbreviation',
            field=models.CharField(max_length=20, verbose_name='Аббревиатура подразделения'),
        ),
        migrations.AlterField(
            model_name='university_unit',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название подразделения'),
        ),
    ]
