# Generated by Django 4.1.7 on 2023-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_auditorium_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university_unit',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название подразделения'),
        ),
    ]
