# Generated by Django 4.1.7 on 2023-03-11 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('amount_people', models.IntegerField(blank=True, default=0)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
                ('date', models.DateField(default=datetime.date(23, 1, 10))),
                ('info', models.TextField()),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('datetime_approved', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_TimetableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('info', models.TextField(blank=True)),
            ],
        ),
    ]
