# Generated by Django 4.1.7 on 2023-03-11 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableitem',
            name='auditorium',
            field=models.ManyToManyField(blank=True, to='users.auditorium'),
        ),
        migrations.AddField(
            model_name='timetableitem',
            name='organazer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableitem',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.type_timetableitem'),
        ),
        migrations.AddField(
            model_name='timetableitem',
            name='who_approved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
