# Generated by Django 4.1.7 on 2023-04-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University_Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='University_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('abbreviation', models.CharField(max_length=10)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('area', models.IntegerField(blank=True)),
                ('capacity', models.IntegerField(blank=True)),
                ('info', models.TextField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.university_building')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.auditorium_type')),
                ('university_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.university_unit')),
            ],
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='auditorium',
            field=models.ManyToManyField(blank=True, to='timetable.auditorium'),
        ),
    ]
