# Generated by Django 4.1.7 on 2023-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditorium_type_university_building_university_unit_and_more'),
        ('timetable', '0003_auditorium_type_university_building_university_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableitem',
            name='auditorium',
            field=models.ManyToManyField(blank=True, to='users.auditorium'),
        ),
        migrations.DeleteModel(
            name='Auditorium',
        ),
        migrations.DeleteModel(
            name='Auditorium_Type',
        ),
        migrations.DeleteModel(
            name='University_Building',
        ),
        migrations.DeleteModel(
            name='University_Unit',
        ),
    ]
