# Generated by Django 4.1.7 on 2023-05-08 11:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_university_unit_abbreviation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0004_alter_timetableitem_auditorium_delete_auditorium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetableitem',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='timetableitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает одобрения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='amount_people',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество человек'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='auditorium',
            field=models.ManyToManyField(blank=True, to='users.auditorium', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='date',
            field=models.DateField(default=datetime.date(23, 1, 10), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='datetime_approved',
            field=models.DateTimeField(null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='end_time',
            field=models.TimeField(blank=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='info',
            field=models.TextField(verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='organazer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответсвенный'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='start_time',
            field=models.TimeField(blank=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.type_timetableitem', verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='timetableitem',
            name='who_approved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='who_approved', to=settings.AUTH_USER_MODEL, verbose_name='Кто одобрил'),
        ),
    ]
