# Generated by Django 4.1.7 on 2023-05-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_remove_timetableitem_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидает одобрения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
