# Generated by Django 4.1.7 on 2023-09-25 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableitem',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.type_timetableitem', verbose_name='Тип мероприятия'),
        ),
    ]
