# Generated by Django 4.1.7 on 2023-10-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_timetableitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='type_timetableitem',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
