# Generated by Django 4.1.7 on 2023-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0009_alter_timetableitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableitem',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название'),
        ),
    ]
