# Generated by Django 4.1.7 on 2025-11-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0010_alter_timetableitem_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Week',
        ),
    ]
